// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzelicznikMVVM.Baza_danych.Context;

namespace PrzelicznikMVVM.Bazadanych.Migrations
{
    [DbContext(typeof(PrzelicznikDbContext))]
    partial class PrzelicznikDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PrzelicznikMVVM.Baza_danych.Model.Jednostka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodzajId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RodzajId");

                    b.ToTable("Jednostki");
                });

            modelBuilder.Entity("PrzelicznikMVVM.Baza_danych.Model.PrzelicznikJednostek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocelowaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocelowaJednostkaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WartoscPrzelicznika")
                        .HasColumnType("REAL");

                    b.Property<int?>("ZrodloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZrodloJednostkaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocelowaId");

                    b.HasIndex("ZrodloId");

                    b.ToTable("PrzelicznikJednostek");
                });

            modelBuilder.Entity("PrzelicznikMVVM.Baza_danych.Model.Rodzaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rodzaje");
                });

            modelBuilder.Entity("PrzelicznikMVVM.Baza_danych.Model.Jednostka", b =>
                {
                    b.HasOne("PrzelicznikMVVM.Baza_danych.Model.Rodzaj", "Rodzaj")
                        .WithMany()
                        .HasForeignKey("RodzajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodzaj");
                });

            modelBuilder.Entity("PrzelicznikMVVM.Baza_danych.Model.PrzelicznikJednostek", b =>
                {
                    b.HasOne("PrzelicznikMVVM.Baza_danych.Model.Jednostka", "Docelowa")
                        .WithMany()
                        .HasForeignKey("DocelowaId");

                    b.HasOne("PrzelicznikMVVM.Baza_danych.Model.Jednostka", "Zrodlo")
                        .WithMany()
                        .HasForeignKey("ZrodloId");

                    b.Navigation("Docelowa");

                    b.Navigation("Zrodlo");
                });
#pragma warning restore 612, 618
        }
    }
}
