// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektUczniowie.Baza_danych.Context;

namespace ProjektUczniowie.Bazadanych.Migracja
{
    [DbContext(typeof(UczniowieDbcontext))]
    [Migration("20220323085630_PierwszaMigracja")]
    partial class PierwszaMigracja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("ProjektUczniowie.Baza_danych.Model.Klasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaKlasy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klasy");
                });
#pragma warning restore 612, 618
        }
    }
}
